[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dashboard"
dynamic = ["version"]
description = "Dashboard for LizardByte"
requires-python = ">=3.14"
license = {text = "MIT"}
authors = [
    {name = "LizardByte", email = "lizardbyte@users.noreply.github.com"}
]

dependencies = [
    "cloudscraper==1.2.71",
    "crowdin-api-client==1.26.0",
    "ipython==9.10.0",
    "itables==2.7.0",
    "notebook==7.5.4",
    "pandas==3.0.1",
    "pillow==12.1.1",
    "plotly==5.24.1",
    "pygithub==2.8.1",
    "python-dotenv==1.2.1",
    "requests==2.32.5",
    "svgwrite==1.4.3",
    "tqdm==4.67.3",
    "unhandled_exit==1.0.0",
]

[project.optional-dependencies]
dev = [
    "nb-clean==4.0.1",
    "nbqa[toolchain]==1.9.1",
]

[project.urls]
Homepage = "https://app.lizardbyte.dev/Sunshine"
Repository = "https://github.com/LizardByte/Sunshine"
Issues = "https://github.com/LizardByte/Sunshine/issues"
